### ISSUE TITLE
Erro Electron

### ISSUE THREAD

**Issue by erick-rssouza** [marcosroriz/sete#119]
Alguém passou por isso?

Error: Could not detect abi for version 24.1.3 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron
    at Object.getAbi (/home/suporte/sete/node_modules/electron-rebuild/node_modules/node-abi/index.js:36:9)
    at Rebuilder.get ABI [as ABI] (/home/suporte/sete/node_modules/electron-rebuild/src/rebuild.ts:121:33)
    at ModuleRebuilder.prebuildNativeModuleExists (/home/suporte/sete/node_modules/electron-rebuild/src/module-rebuilder.ts:164:142)
    at Rebuilder.rebuildModuleAt (/home/suporte/sete/node_modules/electron-rebuild/src/rebuild.ts:260:31)
    at Rebuilder.rebuild (/home/suporte/sete/node_modules/electron-rebuild/src/rebuild.ts:189:9)
    at /home/suporte/sete/node_modules/@electron-forge/core/src/util/rebuild.ts:33:5

**Comment by marcosroriz** [comment]
Oi, qual versão do node você está usando?
É que o projeto tá em uma versão antiga do nodejs. (v12)
Temos que atualizar algumas questões para migrarmos para a nova versão.

**Comment by erick-rssouza** [comment]
Estou usando a v18.16.0, npm 9.6.6

Em qui., 4 de mai. de 2023 às 09:25, Marcos Roriz ***@***.***>
escreveu:

**Comment by ArthurLucasDev** [comment]
Boa tarde! @erick-rssouza como conseguiu resolver?
